# Generated by Django 4.0.8 on 2023-11-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_genre_movie_genres_series_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
