# Generated by Django 4.0.8 on 2023-11-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_genre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
