# Generated by Django 4.0.8 on 2023-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_movie_trailer_url_series_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='iframe_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='iframe_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
