# Generated by Django 4.0.8 on 2023-11-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_remove_series_iframe_url_episode_iframe_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'title')},
        ),
    ]
