# Generated by Django 4.0.8 on 2023-11-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_alter_episode_options_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
    ]
