# Generated by Django 4.0.8 on 2023-11-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
    ]
