# Generated by Django 4.0.8 on 2023-11-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_alter_episode_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season']},
        ),
    ]
